name: mks_ex_dart_interfaces
description: Mukeisoft-LLC example for protocol buffers.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  protobuf: ^2.0.0
  grpc: ^3.0.2

dev_dependencies:

